### ISSUE TITLE
UI Component: Task Manager Task Bar

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#1254]
### Is your feature request related to a problem? Please describe

As a developers there are long lasting tasks that I can perform directly from the tool like building an image, podifying, deploying to kubernetes. I should be able to go to another part of the UI, while the task is getting performed in background, but still be able to get back to that task later on (or to check if an error happened).

### Describe the solution you'd like

A task manager, that allows the user to know the tasks that are getting (or have been) executed in background.

### Additional context

This issue is built on by https://github.com/containers/podman-desktop/issues/1271

**Comment by mairin** [comment]
:wave: Here's a quick mockup of what I was thinking could be done with task management.

![Screenshot from 2023-01-25 12-59-52](https://user-images.githubusercontent.com/799683/214651925-788d7c97-9946-4954-9ca4-2ff1d8e8f06a.png)


1. **Top bar** - shows the notification icon lit up. It says there are 3 new notifications. It might be nice to have a quick animation (not loop) after the long-running process is kicked off so the user knows it's accessible from that area.
2. **Middle bar** - shows if you click the notification bell icon, a panel slides out in the bottom app window bar. Here it shows 3 tasks with progress bars.
3. **Bottom bar** - if you hover on a task name + progress bar, it will light up, and if you click it (or hover long enough, or both?) a popup appears with some more details about the task and a button to relaunch the window if it is closed / lost from where the task is running with the full details.

Thoughts about this? Is this a good rough approach? 

**Scaling to a larger number of tasks**

~~I was thinking if we had more tasks than could be displayed in the bar, we could do a horizontal scroll kind of thing (without the scrollbar) and have a < arrow on one side and a > arrow on the other to page through the tasks. I assume iwth this, of course, that there wouldn't be much more than 7-10 long running tasks at any time. For that scale, might be better to have a separate page instead.~~

We discussed at the UI checkin weekly meeting today that we should just display the most recent running task. If a new long running task starts and finishes on top of the 2nd oldest long running tasks, it should show a short-lived "complete" (or "failed") message, and then older running task should then reappear in the single slot for longer running tasks.

**Highlight on icon / "new"**

I'm not 100% sure yet how to treat tasks the user hasn't yet viewed in the task manager vs ones they already saw. For example, should the bell only be lit up with the number of tasks that haven't been viewed yet? ([That's how Patternfly seems to handle this](https://www.sketch.com/s/729c2eee-e8b6-4fcd-8a79-f6faa8c30f89/a/VaDQ1o).) And we would rely on users to click on the bell again to check up on them? Could be okay, looking for other opinions here. 

**Dark mode palette for pop up**

Right now the pop up is using a light mode palette but it might be better to have a dark mode palette for it (or at least the option. I need to work on that.)

(Here is a quick interactive clickable prototype - only task #3 is hooked up. [https://design.penpot.app/#/view/c1a43240-198d-11ed-817f-f940e3befd53?page-id=69ab1f6d[…]tions&index=1&share-id=4755a563-5b43-8015-8001-f5d0015e457a](https://design.penpot.app/#/view/c1a43240-198d-11ed-817f-f940e3befd53?page-id=69ab1f6d-063f-8058-8001-f59edcd3abfa&section=interactions&index=1&share-id=4755a563-5b43-8015-8001-f5d0015e457a) ) (edited)

**Tasks for Mo:**
- [x] Come up with dark mode palette for pop up
- [x] ~~Mockup < > horiz scrolling area~~ (we decided to only show one task in the bar and lean more on the "all tasks" area.)
- [ ] Distinguish between active tasks vs one-time status notices (e.g. complete! or failed!)
- [ ] Define which tasks are long-running and which are not and will not show up here.
- [x] Show how long-running tasks that we don't have progress/status data for (any at all, or only in stages) could look
- [x] Add an "All Jobs" button to view all active tasks + notifications in one screen (we will use the bell icon)
- [ ] Mockup to show switch over from shorter newer long running task to longer newer-1 long running task
- [ ] ~~Mock up "All Jobs" screen~~ (deferring to sprint 232.)

**Comment by mairin** [comment]
**Updated Taskbar Mockup:**

- We decided to only have one slot for showing a long-running task directly in the bottom bar. No sliding drawer mechanism.
- The single slot will display the most recently-launched long-running task's progress (either in terms of a progress bar, a stage / subway map, or an elapsed time measure) 
- If a shorter, more-recent long-running task eclipsis a longer, recent-1 long-running task, a brief completion message will be shown in the slot area, and then the message will auto-dismiss and pick the recent-1 (now recent-0) longer long-running task.
- We discussed that sometimes we have progress information / status, sometimes we just know about progress through stages and not as a %, and sometimes we know very little about progress other than it's still active, complete, or failed.

![Screenshot from 2023-01-26 14-51-43](https://user-images.githubusercontent.com/799683/214947589-2472cff9-9e24-445f-85c3-b9af9e036720.png)

**Color Palette Options for Dark  Mode**

Here are two options that could work:
![Screenshot from 2023-01-26 15-28-19](https://user-images.githubusercontent.com/799683/214949002-89b7a8cf-8ed2-41cf-9d81-67fa434f3390.png)

**Comment by mairin** [comment]
This is the latest version of the design which I hope can be mostly complete for the bar:

![Task Manager Bar Popup](https://user-images.githubusercontent.com/799683/217667559-37c38448-32d8-46aa-a656-87528eeb9ef0.png)

![Empty List (1)](https://user-images.githubusercontent.com/799683/217668311-2fea8d46-db0e-47fd-8c6c-c8acfcba928e.png)


This is a code pen to show a short loop animation we could do when a new task is added to the popup:
https://codepen.io/mairindubh/pen/abjRGmG

**Comment by mairin** [comment]
Issue for implementation:
https://github.com/containers/podman-desktop/issues/1411

**Comment by mairin** [comment]
Closing as initial design complete, implementation with commence in #1411 :)
