### ISSUE TITLE
Enhance CRC extension to allow deployment from setup

### ISSUE THREAD

**Issue by gbraad** [containers/podman-desktop#1419]
### Epic domain

The current CRC extension has basic integration with the tool. It is capable of basic interaction with the daemon to inspect the running status. This task is about enhancing the extension to install and configure the deployment.

What is missing is the following (given in order of priority):
  * Installation and setup
  * Deployment of the instance (start)
  * Preset selection (config option)
      * OCP (default)
      * podman
      * microshift
  * Handle pull-secret
  * Progress tracking of the install
  * Configuration of the instance
      * Disk-size
      * vCPU
      * Memory
  * Removal of the instance (delete)

### Dependencies

  * HTTP API versioning (optional);  
    https://github.com/crc-org/crc/issues/2543 (feature compatibility for the CRC extension)
  * Remove tray from the current install payload (essential);  
    https://github.com/crc-org/crc/issues/762

**Comment by gbraad** [comment]
We have moved the extension to ouro nw repository to speed up development (not being slowed down by merges and reviews related to static text and missing functionality), however we will encounter other issues, such as the lack of an API to handle external extensions, and the increased need for helper libraries. /cc: @evidolob

**Comment by gbraad** [comment]
This would be the top 4 as of now, as this allows us to replicate the functionality of our current tray
 - [ ] https://github.com/containers/podman-desktop/issues/1890 for clipboard
 - [ ] https://github.com/containers/podman-desktop/issues/1891 for opening external
 - [ ] https://github.com/containers/podman-desktop/issues/1920 pullsecret request dialog
 - [ ] https://github.com/containers/podman-desktop/issues/1919 the please download us dialog
