### ISSUE TITLE
Installation process verification for local and platform dependent builds

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#1958]
### Epic domain

We have available multiple ways how to install podman desktop. This intents to automate verification of each particular installation processes based on OS platform. We will start with these methods, where we can actually build the executable/msi/flatpak,tar from source and test it. 

### Additional context

* Collect requirements, how to build installable artifacts, document installation process and verification methods
- [x] Document installation process (steps) on win - #1961
- [x] Document installation process (steps) on linux - #1959 
- [ ] Document installation process (steps) on mac OS - #1962

* Setup pipeline for installation verification
- [ ] Implement on CI for windows - #1966 
- [ ] Implement on CI for Linux - #1960 
- [ ] Implement on CI for mac - #1967 

ToDo:
* Migrate to GHA if necessary - for available hosted runners
* Extend tests to all required OSes defined in supported configuration
* Extend tests to include all options of installation - some cannot be done before release (flathub, chocolatey, scoop, etc.)
