### ISSUE TITLE
UI Fit & Finish review

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2158]
Review of UI for fit & finish (WIP)

- [x] FILED **Containers Tab**  Set header with action buttons to fixed positioning, so buttons are always accessible while you make / modify your container selection. [filed as https://github.com/containers/podman-desktop/issues/2637]
- [x] FILED **Containers Tab** Convert "Create a container" button => two button dialog into a single drop down button with two options. [filed as https://github.com/containers/podman-desktop/issues/2639]
- [x] FILED **Containers Tab** Podify + Delete buttons always visible, but dimmed until a selection is made. [filed as https://github.com/containers/podman-desktop/issues/2644 ]
- [x] FILED **Containers Tab** Sortable columns in table [filed as https://github.com/containers/podman-desktop/issues/2645 ] 
- [x] **Containers Tab** Expander/closer for extension icons in main nav [filed as https://github.com/containers/podman-desktop/issues/2677 ]
- [x] **Containers Tab** ~~Fixed position / high Z-layer on Settings icon in main nav~~
- [x] **Containers Tab** ~~Drop shadows on header and main nav~~
- [x] **Containers Tab** Column groups for table + custom column selection [filed as https://github.com/containers/podman-desktop/issues/2679 ]
- [x] **Containers Tab** Column for container build age (disambiguate between build age and uptime?) [filed as https://github.com/containers/podman-desktop/issues/2678 ]
- [x] **Titlebar** ~~Remove double titlebar on Windows and Linux~~
- [x] **Settings** ~~Header titles across pages seems to be missing top margins~~
- [x] **Titlebar** ~~when narrow, adds extra unneeded vert padding, "mb-4 md:mb-0" should just be mb-0~~

**Comment by mairin** [comment]
We fixed what was possible before 1.0, so my plan for this issue is to file the rest of the bigger issues as separate tickets and close this.

**Comment by mairin** [comment]
got these all filed :) :) :) closing
