### ISSUE TITLE
Podman Desktop - Windows Installer

### ISSUE THREAD

**Issue by nichjones1** [containers/podman-desktop#302]
### Epic domain

All Podman Desktop issues relating to Windows Installer will be linked here

### Additional context

##Subtasks

- [x] #185 
- [x] #225 
- [x] #282 
- [x] #270 
- [x] https://github.com/containers/podman/issues/14698
- [x] https://github.com/containers/podman/issues/14416
- [x] https://github.com/containers/podman/issues/14589

- _No response_

**Comment by benoitf** [comment]
closing as all tasks have been completed in 0.11
