### ISSUE TITLE
Update the troubleshooting guide

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#3045]
- [ ] Update outdated info https://github.com/containers/podman-desktop/pull/3088 https://github.com/containers/podman-desktop/pull/3089
- [ ] Should take the things we suggest to issues into account when talking with users and helping debug in the troubleshooting guide
- [x] Add troubleshooting info for: https://github.com/containers/podman/issues/19554
- [ ] Add troubleshooting info for: https://github.com/containers/podman-desktop/issues/2806
- [ ] Add troubleshooting info for: https://github.com/containers/podman-desktop/issues/1633
- [ ] Add troubleshooting info for: https://github.com/containers/podman-desktop/issues/2794
- [x] Should update the troubleshooting guide with the new troubleshooting page feature https://github.com/containers/podman-desktop/pull/3083
