### ISSUE TITLE
E2E test cases automatization

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3931]
### Epic domain

Tracker and overall progress issue for automation status of E2E test cases. Depending on test nature we want to have them automated in various scenarios on a required infrastructure.
* Tests that are run on PR check on GHA infra
* Tests that are run nightly on particular platform on public infra (Windows + Mac)
* tests that are run weekly in internal infrastructure

### Additional context

* [x] Automate Welcome Page handling test case - #2707 
* [x] Automate Pull image scenario on GHA - #2848 
* [x] Automate Containers handling scenario GHA - #2851, #3434
* [x] Automate Dev Sandbox Extension Installation verification - #3339 
* [x] Automate OpenShift Local extension installation verification - #3340 
* [x] Automate Pod Creation scenario - #2852 
* [x] #5197
* [x] #5196
* [x] #4822
* [x] #4823
* [x] #4794
* [ ] Automate Podman machine handling scenario - windows
* [x] #4795
* [ ] Automate Building an image scenario
* [ ] Automate Play Kubernetes YAML scenario
* [ ] Automate Dev Sandbox resource Creation scenario
* [ ] Automate Kind cluster creation scenario
* [ ] Automate Deploy to Kubernetes - Kind
* [ ] Automate Deploy to Kubernetes - Dev sandbox
* [ ] Automate Deploy to Kubernetes - OpenShift Local
* [ ] [Automate OpenShift Local installation scenario (Using GOAX)](https://github.com/containers/podman-desktop-e2e/issues/61)
* [ ] Automate OpenShift local resource creation - OpenShift
* [ ] Automate OpenShift local resource creation - Microshift
* [x] Automate podman Installation (GOAX) - [ext. link](https://github.com/containers/podman-desktop-e2e/pull/15)

**Comment by odockal** [comment]
Closing in favor of other Epics that now track the particular feature automation progress.
