### ISSUE TITLE
Improvement to a dedicated testing framework to suit Podman Desktop needs

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3932]
### Epic domain

Test-framework customization to better align with Podman Desktop testing needs. Will cover ie. improvement in pre-post test hooks, test artifacts customization - video recording, screenshots on failure, error logs collecting, Page object model implementations, test application runner implementation, global and local setup files, test result creation, etc.

### Additional context

* [x] E2E playwright tests spawn electron app in a right way - #1780
* [x] Testing application can set a custom configuration folder - #2837 
* [x] Podman desktop runner  - #3302
* [x] Initial Page Object model implementation - #3288 
* [x] Introduce global settings file - #3290
* [x] Override AfterEach test hook to take a screenshot - #3409
* [x] Suite concept for e2e tests (Moving to #7970)
* [x] Improve video capturing feature - #3337
* [x] Screenshot capabilities in afterAll test hook - #3554 - moved under #7970
* [x] Running e2e tests agains a podman desktop binary - #3744 
* [x] Implementation of Waiters functionality
* [x] Electron application handling on test in error state - one faling test sometimes does not allow to run subsequent tests (N/A)
* [x] #4780
