### ISSUE TITLE
Stabilization of automated tests, infrastructure and CI

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3936]
### Epic domain

Placeholder for issues aimed at flaky tests, infrastructure work and maintenance, automation stabilization.

### Additional context

* [x] GitHub API rate limit exceeded on CI - contour file download limit - #2248 
* [x] Flaky e2e.spec.ts - #2312
* [x]  Podman version used on GHA ubuntu runner is flaky - #3434
* [x] Fix e2e smoke test instability - #3581
* [x] https://github.com/containers/podman-desktop-e2e/issues/32 
* [x] https://github.com/containers/podman-desktop-e2e/issues/29
* [x] #4814 
* [x] #4817 
* [x] #5303 
* [x] #5067 
* [x] #5325 
* [x] #4929
* [x] #4866 
* [x] #4877 
* [x] #4905 
* [x] #4968
* [x] #4983 
* [x] #5032 
* [x] #5304 
* [x] #5303
* [x] https://github.com/containers/podman-desktop-e2e/issues/81

**Comment by odockal** [comment]
I have linked all stability related issues that were resolved in 2023 and I am closing this epic placeholder. Will open new to hold a list of stability issues in the 2024.
