### ISSUE TITLE
Interoperability testing for Podman Desktop and underlying projects

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3937]
### Epic domain

Tracker for interoperability testing tasks. Podman desktop uses other projects and this requires proper testing processes and procedures (automated) to be at place. 
* Podman
* Dev SandBox
* OpenShift Local
* Docker
* Lima
* Kind, compose
* Kubernetes
* Etc.

### Additional context

* [ ] E2E tests are run in restricted environment - #2868
* [ ] Integrate podman desktop e2e tests into windows pipeline - [ext.link](https://github.com/containers/podman-desktop-e2e/issues/16)
* [ ] Setup a pipeline that triggers Podman Desktop e2e tests against podman nightly build - [ext. link](https://github.com/containers/podman-desktop-internal/issues/101)
* [ ] Triggers E2E tests on OpenShift local extension release and have a weekly based job testing nightly builds
* [ ] Triggers E2E tests on OpenShift local release and have a weekly based job testing nightly builds
* [ ] Triggers E2E tests on Dev Sandbox extension release and have a weekly based job testing nightly builds
