### ISSUE TITLE
Improve doc readability

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4300]
### Is your enhancement related to a problem? Please describe

In many of the Documentation pages we have sections for:
- Initial title/text 
- Prerequisites
- Procedure
- Additional Resources
- Next Steps
- Tags
and a link to edit and a bar for previous/next steps.

In many of the pages the sections titles and links dwarf the actual content - e.g. in some of the installation pages the content is only 2 steps, but the pages themselves are 20+ lines long. This makes it really hard to scan for the 'important bits' quickly and makes the pages feel longer than they actually are.

Also, Next steps rarely match the Next button.

FYI @themr0c 

### Describe the solution you'd like

Some suggestions:
- [ ] Use subtle header/font size or other CCS changes to minimize some of the less important areas, or conversely highlight the procedure. e.g. additional resources could be in a smaller font, light grey instead of white, or hidden in a drop-down by default. #4315
- [ ] Make the 'Edit this page' button a bit less conspicuous, e.g. just have an edit icon by the title. #4314
- [ ] Do we need to show tags at all? If so, could remove the word Tags. #4309 
- [ ] Remove the previous/next bar (or remove Next Steps). #4311

**Comment by lstocchi** [comment]
@deboer-tim I updated the tag, I guess it was the wrong fab 😆

**Comment by themr0c** [comment]
I am all for entirely removing tags:

- The tag pages are not indexed by search engines.
- The usage statistics show the visitors don't use the tag pages to navigate.
- They clutter the pages.

**Comment by slemeur** [comment]
I'm closing this issue, as I think we need to address this, in a more granular and actionnable way, section per section.
