### ISSUE TITLE
Apply naming pattern for onboarding ids

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4911]
### Is your enhancement related to a problem? Please describe

The ids used during onboarding aren't especially obvious when you look at logs or telemetry data, e.g. picking on compose:

- checkComposeDownloaded - IMHO it checks for 'local install'
- startComposeDownload - doesn't actually download, it just tells the user it will
- composeDownloaded is the success equivalent of composeFailedDownload

### Describe the solution you'd like

We should define some simple patterns that make onboarding ids consistent and fairly obvious, and apply it to both podman and compose extensions. It should have:

- clear differentiation between (a pattern for) ids for content vs command
- similar pattern for success vs failure screens (e.g. '.success' and '.failure')
- pattern for welcome or summary content pages

Do we need the extension in the id? (e.g. do compose ids need to include 'compose' or is that always obvious in context and could be removed?)

It should be obvious from the ids what the content shows or command does.

## Rules
- steps displaying information are suffixed with `View`
- steps executing a command are suffixed with `Command`
- steps with a state='failed' are suffixed with `Failure`
- steps with a state='completed' are suffixed with `Success`

## Acceptance criteria

- [x] modify Podman onboarding (#4935)
- [x] Modify Compose onboarding (#4948)
- [ ] Update documentation to describe the rules (blocked by PR 4837)
- [x] Raise warnings when extension is loaded if rules are not respected (#4951)
