### ISSUE TITLE
Minikube Extension QE Coverage

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5486]
### Epic domain

After the new feature implemented mainly in podman-desktop/podman-desktop#2610, we need to make sure, to have QE coverage plan for this feature and taken into account.

Consists of multiple steps
* [x] https://github.com/containers/podman-desktop-internal/issues/135
* [ ] Minikube Page ARIA functionality (please create an issue if needed and link it here)
* [x] https://github.com/containers/podman-desktop-extension-minikube/issues/137
* [x] https://github.com/containers/podman-desktop-extension-minikube/issues/138
* [x] https://github.com/containers/podman-desktop-extension-minikube/issues/140
* [x] https://github.com/containers/podman-desktop-extension-minikube/issues/139
* [x] podman-desktop/extension-minikube#298
* [x] podman-desktop/extension-minikube#299
* [x] podman-desktop/extension-minikube#239
* [x] podman-desktop/extension-minikube#240

Feature's codebase: https://github.com/containers/podman-desktop-extension-minikube

**Comment by odockal** [comment]
As discussed with @amisskii, we will start working on the issues under this epic.

**Comment by odockal** [comment]
@amisskii I think we are good to close the epic, right? Reopen if you disagree.
