### ISSUE TITLE
QE Coverage for SSO extension

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5787]
### Epic domain

The tasks in regard of QE coverage for SSO extension for podman desktop. 

Consists of multiple steps
* [ ] QE doc: document steps necessary to validate installation of extension and prepare examples and steps to verify its functionality
* [ ] Propose a test cases for a release testing of the extension
* [ ] Create basic e2e tests to validate extension installation and functionality
* [ ] Create CICD pipeline to run extension e2e tests.
* [ ] Ensure automation works on all relevant platforms
