### ISSUE TITLE
Dev Sandbox Resource QE Coverage

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5977]
### Epic domain

Kind feature was implemented, we need to make sure, to have QE coverage plan for this feature and taken into account.

Consists of multiple steps

* [ ] QE doc: document Kind feature, prepare examples and steps to verify its functionality
* [ ] Kind/Resources/Deployments ARIA functionality
* [ ] Kind E2E Test implementation
* [ ] Kind E2E Test automation (Windows, Mac, Linux)
