### ISSUE TITLE
epic(UI): integrating Storybook for our ui library

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6338]
### Is your feature request related to a problem? Please describe

We need to integrate the Storybook framework in our codebase

### Describe the solution you'd like

Here is a roadmap for proceeding with Storybook

- [x] #7328
- [x] https://github.com/containers/podman-desktop/issues/7437
- [x] https://github.com/containers/podman-desktop/issues/7438
- [x] https://github.com/containers/podman-desktop/issues/7439
- [x] https://github.com/containers/podman-desktop/issues/7440
- [ ]  feat(UI): adding Visual tests for the UI components
- [x] https://github.com/containers/podman-desktop/issues/7441

### Additional context

**Prior to implementation:**

Explore frameworks and see what could be their pro/cons

- [x] #7218
- [x] #7219

After a vote, Storybook has been choosen, matching our requirement, and expectations

**Comment by axel7083** [comment]
I updated my branch with latest `8.0.9` version of `Storybook` (See https://github.com/axel7083/podman-desktop/tree/feature/storybook)

You can try it by checkout and run `cd ./storybook && yarn run storybook`

**Comment by benoitf** [comment]
all issues have been done, closing
