### ISSUE TITLE
Epic: Implement manifests for Podman Desktop

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#6526]
### Epic domain

Within Podman Desktop, it would be beneficial to do the equivalent to the Podman CLI:

```
# First, initialise the manifest
podman manifest create <image name>

# Build the image attaching them to the manifest
podman build --platform linux/amd64,linux/arm64  --manifest <image name>  .

# Finally publish the manifest
podman manifest push <image name>
```

In order to create a multi-platform / multi-arch singular image.

Implementation tasks (in order):
- [x] Add manifest API to Podman Desktop https://github.com/containers/podman-desktop/issues/6527
- [x] Be able to create a multi-platform / multi-arch manifest from within the UI on the "Build Image" screen https://github.com/containers/podman-desktop/issues/6236
- [x] Be able to list manifests on the page https://github.com/containers/podman-desktop/issues/6529
- [x] Basic view details of the manifest https://github.com/containers/podman-desktop/issues/7255
- [x] More advanced view details of the manifest https://github.com/containers/podman-desktop/issues/7270
- [x] Add functions such as push manifest, rename manifest, etc similar to image actions. https://github.com/containers/podman-desktop/issues/7041
- [x] Show child images / <none> images below the manifest: https://github.com/containers/podman-desktop/issues/7181

### Additional context

Reference: https://github.com/containers/podman-desktop/issues/6236

**Comment by cdrage** [comment]
All features are done :) Closing!
