### ISSUE TITLE
listImages API call should use libpod API against podman

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#6676]
### Is your enhancement related to a problem? Please describe

Splitting this issue into two, as part of https://github.com/containers/podman-desktop/issues/6623 which will implement the internal call.

This issue relates to listImages:

- When calling Docker / other similar engines, use compat api
- When calling Podman, use libpodApi as that will also return manifests.

### Describe the solution you'd like

listImages use libpod api when calling against podman so that we can retrieve manifests.

**Comment by cdrage** [comment]
I've created a POC PR to outline some issues with adding manifests to the list images API: https://github.com/containers/podman-desktop/pull/6688

Unfortunately there are multiple issues with adding the podman list images to the listImages API, as it adds manifests which PD does not support right now and outlined in the video below:

- We cannot safely determine what is a manifest vs an image as there is no tag, so we cannot indicate to the user which is manifest vs image
- Cannot create a container from the manifest (it is blank)
- If creating an image did work, we would have to ask which architecture they want to use
- Cannot delete a manifest
- Cannot delete any manifest children
- Inspect is blank
- History is blank 

https://github.com/containers/podman-desktop/assets/6422176/b1f9d9c5-f5a5-44df-96c1-190975c645a9


https://github.com/containers/podman-desktop/assets/6422176/529a625c-497f-4b29-8fb6-65f4796d049b


I believe that we should not add the podmanListImages API to `listImages` right now as it will mess up the podman desktop UI until we can fully support manifests.

I'm unsure how to proceed, the only thing I can think of right now is that we have a separate API call (podmanListImages) as previously discussed so extensions may use that list images endpoint (ex. bootc), so that we can get the manifest / determine it ourselves.

**Comment by cdrage** [comment]
After a brief conversation with @benoitf we've come up with the following solutions:

- [x] Add a "isManifest" boolean value for any images which are suspected to be a manifest. We cannot safely determine if they are a manifest or not due to podman not returning the type, but we can however do an estimated guess. https://github.com/containers/podman-desktop/issues/6690 and #6691 
- [ ] Add a configuration property that is HIDDEN and enables / disables listImages returning images using the libPod API, that can be safely turned off / on at a seconds notice in case we encounter any issues, updated in this issue: https://github.com/containers/podman-desktop/issues/6622
- [ ] Hide manifests from the UI by filtering them out in the images store until we can safely add manifests. https://github.com/containers/podman-desktop/issues/6689
