### ISSUE TITLE
Kubernetes epic: Add "advanced" sections (daemonsets, statefulsets, jobs, etc.)

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7192]
### Epic domain

Related to https://github.com/containers/podman-desktop/issues/7190

There are other parts of Kubernetes that could be added such as "advanced" that could possibly be toggled / shown as an advanced section.

The missing ones would be:

**Should be added:**
- [ ] DaemonSets https://github.com/podman-desktop/podman-desktop/issues/11113
- [ ] StatefulSets https://github.com/podman-desktop/podman-desktop/issues/11114
- [ ] ReplicaSets https://github.com/podman-desktop/podman-desktop/issues/11116
- [x] Jobs https://github.com/podman-desktop/podman-desktop/issues/11112
- [x] Pods (https://github.com/podman-desktop/podman-desktop/issues/8818)
- [x] CronJobs (https://github.com/podman-desktop/podman-desktop/issues/10560)

**IMHO should not be added / super advanced features:**
- Ingress Classes (more administrative)
- Storage Classes  (more administrative)
- Replication Controllers (controlled by deployments, seldom used)
- Resource Quotas (admin use)
- Limit Ranges (admin use)
- HPA (admin use, usually created by deployment)
- Pod Disruption Budgets (admin)
- Priority classes (admin)
- Runtime classes (admin)
- Leases (admin)
- Mutating webhook configs (admin)
- Validating webhook configs (admin)
- Endpoints (not needed / created by service)
- Network Policies (admin)
- Port Forwarding (maybe?)

**Comment by axel7083** [comment]
I fear this will not scale in the navbar.. I am against adding all the kubernetes resources in the navbar, even through an advanced flag.

IMO we should only have a Kubernetes icon on the navbar, opening it would lead to a dedicated page, or webview if we want to externalize it. 

Here is a quick mockup, you will clearly see the inspiration from Lens, as it is a tool I am using since a very long time, i feel confortable have all the Kubernetes resources listed in a navigation bar, and it would scale well to those _advanced_ scenarios.

![image](https://github.com/containers/podman-desktop/assets/42176370/3c35612a-dbc6-42f1-95eb-73e060fe4203)

cc @slemeur some opinion ?

**Comment by deboer-tim** [comment]
It is also a question for design, but this issue says 'we should have it', not 'we should have it in the navigator'. Let's not spend time figuring out where future things might go until we are planning to start it.

**Comment by slemeur** [comment]
@axel7083 : I agree that the current navigation for the kubernetes objects does not scale and feels undiscoverable. Between kubernetes objects, extensions, the navigation does not offer a proper way to handle a usable scalable navigation.

I'm +1 on the proposal you have. 
I also believe that we should match the pattern we have in the other extensions with the 2nd sidebar navigation.

**Comment by slemeur** [comment]
I would also like that we have all kubernetes objects under a single menu items. Right now, I don't see the reason why Pods have their primary entry, compared to the other Kubernetes objects (which are also supported by Podman)

**Comment by cdrage** [comment]
Updated the original issue that it's more of a suggestion, rather than "should".

I agree with the points from @slemeur regarding pods, it should be in the Kubernetes section..

We should 100% have a discussion the direction of advanced sections like these before continuing.

**Comment by axel7083** [comment]
Still relevant -

**Comment by jiridostal** [comment]
This epic is currently paused due to the https://github.com/podman-desktop/podman-desktop/issues/11123#issuecomment-3048612846

**Comment by cdrage** [comment]
Closing as not planned (going to k8s dashboard extension)
