### ISSUE TITLE
QE coverage for Podman Remote feature

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#8631]
### Epic domain

Podman Remote feature was added as of 1.12.0 release, we need to make sure to have it covered with tests and automation.

Ref: https://github.com/containers/podman-desktop/issues/279

### Additional context

Consists of multiple steps

* [x] https://github.com/containers/podman-desktop/issues/8453
* [x] podman-desktop/podman-desktop#8632
* [ ] Automate the podman remote test on linux
* [ ] podman-desktop/podman-desktop#9966
* [x] podman-desktop/podman-desktop#8633
* [ ] podman-desktop/e2e#554
* [ ] podman-desktop/podman-desktop#9968
