### ISSUE TITLE
OpenShift Local QE Coverage

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#8638]
### Epic domain

OpenShift Local Extension is part of Podman Desktop platform, we need to make sure, to have QE coverage plan for this feature and taken into account.

### Additional context

Consists of:
* [ ] QE doc: document OS Local Extension feature, prepare examples and steps to verify its functionality
* [ ] Compose a testing sheet for OpenShift Local releases
* [ ] Add OS Local/Resources/Deployments ARIA functionality
* [ ] Basic OpenShift Local Exntesion Installation E2E Test implementation
* [ ] OpenShift Local extension handling in Podman Desktop e2e test
* [ ] Add GHA workflow job running on PR check
* [ ] Add GHA workflow to run e2e tests on Windows
* [ ] Add GHA workflow to run e2e tests on Mac
* Add more e2e tests with use of goax - probably next epic
