### ISSUE TITLE
simplify kubernetes-context-state.ts 

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#8775]
### Is your enhancement related to a problem? Please describe

The [kubernetes-context-state.ts](https://github.com/containers/podman-desktop/blob/main/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts) file is very hard to apprehend due to its complexity and numerous objects definition and implementation in it.

## Types definitions

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L71

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L88

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L102-L104

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L110-L112

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L122-L124

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L149-L151

## Interfaces

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L74

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L80

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L115

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L126

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L166

## Classes definition

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L177

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L205

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L351

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L380

 

### Describe the solution you'd like

Split it in smaller file. At least one per class 

## Pros

- Ease readability
- Reduce the size of the test file

**Comment by feloy** [comment]
Here are the steps I intend to do:

- [x] move `Backoff` class to its own file and add unit tests: #8941
- [x] move `SecondaryResourceWatchersRegistry` class to its own file and give it a more generic name: #8945 
- [x] move `ContextsStates` and related types/interfaces to its own file and public definitions to `/@api/`: #8960
- [x] move state-related functions (`setStateAndDispatch`, `dispatch*`, `getContextsGeneralState`, `getCurrentContextGeneralState`) from `ContextsManager` class to `ContextsStates` class: #9122 
- [ ] remove `kubernetes-` prefix from filenames, as they are already on a `kubernetes/` directory, and rename files/classes to clarify roles: #9164
